{
 "title": "PV",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Produktion [W]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(P_PV{job=\"fronius\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Produktion [W]",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "P_PV{job=\"fronius\", instance=\"192.168.111.150\"}",
     "legendFormat": "aktuell"
    },
    {
     "expr": "avg_over_time(P_PV{job=\"fronius\", instance=\"192.168.111.150\"}[24h])",
     "legendFormat": "mittel"
    },
    {
     "expr": "max_over_time(P_PV{job=\"fronius\", instance=\"192.168.111.150\"}[24h])",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Grid [W]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "P_Grid{job=\"fronius\", instance=\"192.168.111.150\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Verbrauch [W]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "P_Usage{job=\"fronius\", instance=\"192.168.111.150\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Produktion [W]",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "P_Usage{job=\"fronius\", instance=\"192.168.111.150\"}",
     "legendFormat": "aktuell"
    },
    {
     "expr": "avg_over_time(P_Usage{job=\"fronius\", instance=\"192.168.111.150\"}[24h])",
     "legendFormat": "mittel"
    },
    {
     "expr": "max_over_time(P_Usage{job=\"fronius\", instance=\"192.168.111.150\"}[24h])",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Autarkiegrad",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rel_Autonomy{job=\"fronius\", instance=\"192.168.111.150\"}",
     "legendFormat": "Verbrauch"
    }
   ]
  },
  {
   "title": "Produktion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "P_PV{job=\"fronius\"}",
     "legendFormat": "Produktion [W]"
    },
    {
     "expr": "P_Usage{job=\"fronius\", instance=\"192.168.111.150\"}",
     "legendFormat": "Verbrauch [W]"
    }
   ]
  },
  {
   "title": "Grid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "P_Grid{job=\"fronius\", instance=\"192.168.111.150\"} < 0",
     "legendFormat": "Einspeisung"
    },
    {
     "expr": "P_Grid{job=\"fronius\", instance=\"192.168.111.150\"} > 0",
     "legendFormat": "Netzbezug"
    }
   ]
  },
  {
   "title": "Autarkiegrad [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rel_Autonomy{job=\"fronius\", instance=\"192.168.111.150\"}",
     "legendFormat": "Autarkiegrad [%]"
    }
   ]
  },
  {
   "title": "Produktion",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "P_PV{job=\"fronius\", instance=\"192.168.111.150\"}",
     "legendFormat": "Verbrauch"
    }
   ]
  },
  {
   "title": "Produktion",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "P_PV{job=\"fronius\", instance=\"192.168.111.150\"}",
     "legendFormat": "Verbrauch"
    }
   ]
  },
  {
   "title": "Verbrauch",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "P_Usage{job=\"fronius\", instance=\"192.168.111.150\"}",
     "legendFormat": "Verbrauch"
    }
   ]
  }
 ]
}