scrape_configs:

  - job_name: fronius
    metrics_path: /fronius
    params:
      module: [GetPowerFlowRealtimeData]
    static_configs:
      - targets:
        - 192.168.111.209
        - 192.168.111.219
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9116  # The Fronius exporter's real hostname:port.
