{
 "title": "RTR-Netztest",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(download{job=\"rtr-netztest\", quality!~\"good|average|bad\"}[$__interval])",
     "legendFormat": "Download [Mbps]"
    }
   ]
  },
  {
   "title": "Downlink quality",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time(quality{job=\"rtr-netztest\", metric=\"download\", quality=\"good\"}[$__interval]) or on() vector(0)",
     "legendFormat": "{{quality}}"
    },
    {
     "expr": "count_over_time(quality{job=\"rtr-netztest\", metric=\"download\", quality=\"average\"}[$__interval]) or on() vector(0)",
     "legendFormat": "{{quality}}"
    },
    {
     "expr": "count_over_time(quality{job=\"rtr-netztest\", metric=\"download\", quality=\"bad\"}[$__interval]) or on() vector(0)",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(upload{job=\"rtr-netztest\", quality!~\"good|average|bad\"}[$__interval])",
     "legendFormat": "Download [Mbps]"
    }
   ]
  },
  {
   "title": "Uplink quality",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time(quality{job=\"rtr-netztest\", metric=\"upload\", quality=\"good\"}[$__interval]) or on() vector(0)",
     "legendFormat": "{{quality}}"
    },
    {
     "expr": "count_over_time(quality{job=\"rtr-netztest\", metric=\"upload\", quality=\"average\"}[$__interval]) or on() vector(0)",
     "legendFormat": "{{quality}}"
    },
    {
     "expr": "count_over_time(quality{job=\"rtr-netztest\", metric=\"upload\", quality=\"bad\"}[$__interval]) or on() vector(0)",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(ping{job=\"rtr-netztest\", quality!~\"good|average|bad\"}[$__interval])",
     "legendFormat": "Download [Mbps]"
    }
   ]
  },
  {
   "title": "Ping quality",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time(quality{job=\"rtr-netztest\", metric=\"ping\", quality=\"good\"}[$__interval]) or on() vector(0)",
     "legendFormat": "{{quality}}"
    },
    {
     "expr": "count_over_time(quality{job=\"rtr-netztest\", metric=\"ping\", quality=\"average\"}[$__interval]) or on() vector(0)",
     "legendFormat": "{{quality}}"
    },
    {
     "expr": "count_over_time(quality{job=\"rtr-netztest\", metric=\"ping\", quality=\"bad\"}[$__interval]) or on() vector(0)",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min_over_time(download{job=\"rtr-netztest\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(download{job=\"rtr-netztest\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(download{job=\"rtr-netztest\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min_over_time(upload{job=\"rtr-netztest\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(upload{job=\"rtr-netztest\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(upload{job=\"rtr-netztest\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min_over_time(ping{job=\"rtr-netztest\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(ping{job=\"rtr-netztest\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(ping{job=\"rtr-netztest\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RTR-Netztest Download [Mbps]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "download{job=\"rtr-netztest\"}",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "RTR-Netztest RTT [ms]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "ping{job=\"rtr-netztest\"}",
     "legendFormat": "RTT"
    }
   ]
  },
  {
   "title": "RTR-Netztest Upload [Mbps]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "upload{job=\"rtr-netztest\"}",
     "legendFormat": "Upload"
    }
   ]
  }
 ]
}