scrape_configs:

  - job_name: ipinfo
    metrics_path: /ipinfo
    params:
      module: [ipinfo]
    static_configs:
      - targets:
        - ipinfo.io
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9118  # The keenetic exporter's real hostname:port.
