{
 "title": "Keenetik",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{job=\"keenetic\", instance=\"192.168.111.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Public IP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "public_ip{job=\"ipinfo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lease age",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "public_ip{job=\"ipinfo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total traffic in",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "rxbytes{job=\"keenetic\", instance=\"192.168.111.1\", description=\"Telekom Austria\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total traffic out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "txbytes{job=\"keenetic\", instance=\"192.168.111.1\", description=\"Telekom Austria\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpuload{job=\"keenetic\", instance=\"192.168.111.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU load gateway",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpuload{job=\"keenetic\", instance=\"192.168.111.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic fixed line uplink",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(rxbytes{job=\"keenetic\", instance=\"192.168.111.1\", description=\"Telekom Austria\"}[$__rate_interval])",
     "legendFormat": "Traffic in"
    },
    {
     "expr": "increase(txbytes{job=\"keenetic\", instance=\"192.168.111.1\", description=\"Telekom Austria\"}[$__rate_interval])",
     "legendFormat": "Traffic out"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min_over_time(cpuload{job=\"keenetic\", instance=\"192.168.111.1\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 1, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(cpuload{job=\"keenetic\", instance=\"192.168.111.1\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(cpuload{job=\"keenetic\", instance=\"192.168.111.1\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpuload{job=\"keenetic\", instance=\"192.168.111.1\"}",
     "legendFormat": "CPU current"
    },
    {
     "expr": "min_over_time(cpuload{job=\"keenetic\", instance=\"192.168.111.1\"}[$__range])",
     "legendFormat": "CPU min"
    },
    {
     "expr": "avg_over_time(cpuload{job=\"keenetic\", instance=\"192.168.111.1\"}[$__range])",
     "legendFormat": "CPU average"
    },
    {
     "expr": "max_over_time(cpuload{job=\"keenetic\", instance=\"192.168.111.1\"}[$__range])",
     "legendFormat": "CPU max"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "memcache{job=\"keenetic\", instance=\"192.168.111.1\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "membuffers{job=\"keenetic\", instance=\"192.168.111.1\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "memfree{job=\"keenetic\", instance=\"192.168.111.1\"} + swaptotal{job=\"keenetic\", instance=\"192.168.111.1\"}",
     "legendFormat": "memfree"
    },
    {
     "expr": "memtotal{job=\"keenetic\", instance=\"192.168.111.1\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Traffic mobile uplink",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(rxbytes{job=\"keenetic\", instance=\"192.168.111.1\", interface_name=\"UsbQmi0\"}[$__rate_interval])",
     "legendFormat": "Traffic in"
    },
    {
     "expr": "increase(txbytes{job=\"keenetic\", instance=\"192.168.111.1\", description=\"Drei\"}[$__rate_interval])",
     "legendFormat": "Traffic out"
    }
   ]
  }
 ]
}