scrape_configs:

  - job_name: keenetic
    metrics_path: /keenetic
    params:
      module: [system, interface]
    static_configs:
      - targets:
        - 192.168.111.1
        - 192.168.111.3
        - 192.168.111.4
        - 192.168.111.5
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9117  # The keenetic exporter's real hostname:port.

