scrape_configs:

  - job_name: tasmota
    metrics_path: /tasmota
    params:
      module: [StatusSNS]
    static_configs:
      - targets:
        - 192.168.1.150
        - 192.168.1.151
        - 192.168.1.152
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9118  # The Tasmota exporter's real hostname:port.
